export * as ValidatablePattern from "./ValidatablePattern/methods.js"
export * as TokenizablePattern from "./TokenizablePattern/methods.js"
export * as Token from "./Token/methods.js"
export * as EliminablePattern from "./EliminablePattern/methods.js"
export * as Collection from "./Collection/methods.js"
