export * as InputStream from "./InputStream/methods.js"
export * as LimitedStream from "./LimitedStream/methods.js"
export * as NestedStream from "./NestedStream/methods.js"
export * as PredicateStream from "./PredicateStream/methods.js"
export * as ProlongedStream from "./ProlongedStream/methods.js"
export * as StreamClass from "./StreamClass/methods.js"
export * as TransformedStream from "./TransformedStream/methods.js"
export * as TreeStream from "./TreeStream/methods.js"
