export * as IndexMap from "./IndexMap/methods.js"
export * as Parser from "./Parser/methods.js"
export * as Pattern from "./Pattern/methods.js"
export * as Stream from "./Stream/methods.js"
export * as Tree from "./Tree/methods.js"
